name: Wabi-Sabi Stories
title: Wabi-Sabi Stories
description: Sharing stories that serve one another
url: "http://wabisabistories.com"
icon: /images/wss_logo.jpg

fb_appid: 1168945993198378
permalink: /blog/:title/
markdown: rdiscount
excerpt_separator: <!--more-->

highlighter: rouge

defaults: 
-
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
